version: 1.0.{build}
image: Visual Studio 2017

build_script:
  - go build whoami.go
  - docker build -t mplatform/whoami:windows-amd64 -f Dockerfile.windows .

test_script:
  - docker images

deploy_script:
  - ps: >-
      if (Test-Path Env:\APPVEYOR_REPO_TAG_NAME) {

        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

        docker tag mplatform/whoami:windows-amd64 mplatform/whoami:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64

        docker push mplatform/whoami:$($env:APPVEYOR_REPO_TAG_NAME)-windows-amd64

      }
